# Generated by Django 4.2.9 on 2024-01-17 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('shaba_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'بدنه ماشین'), (2, 'شخص ثالث'), (3, 'حوادث'), (4, 'درمان'), (5, 'عمر'), (6, 'واحد مسکونی'), (7, 'مرکز صنعتی'), (8, 'مرکز غیر صنعتی'), (9, 'حمل و نقل'), (10, 'هواپیما')])),
                ('created_at', models.DateField()),
                ('duration', models.IntegerField(choices=[(1, '1 year'), (5, '5 years'), (10, '10 years'), (15, '15 years'), (30, '30 years')])),
                ('cost', models.FloatField(max_length=150)),
                ('payment_kind', models.CharField(choices=[('1', 'yearly'), ('2', 'monthly')], max_length=15)),
                ('consultant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant', to='consultant.consultant')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Insurance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Use_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_content', models.CharField(default='', max_length=500)),
                ('request_answer', models.CharField(default='', max_length=500)),
                ('request_date', models.DateField()),
                ('amount', models.FloatField(default=0, max_length=150)),
                ('documents', models.FileField(default='', upload_to='')),
                ('paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField()),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_insurance', to='insurance.insurance')),
                ('recieve_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='use_insurance', to='insurance.bank_card')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_dates', to='insurance.insurance')),
            ],
        ),
    ]
