# Generated by Django 4.2.9 on 2024-01-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_dates',
            name='paid_date',
            field=models.DateField(null=True),
        ),
    ]
