# Generated by Django 4.2.9 on 2024-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_payment_dates_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_dates',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
