# Generated by Django 4.2.9 on 2024-02-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
        ('insurance', '0004_alter_use_insurance_paid_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_from_consultant', to='consultant.consultant'),
        ),
    ]
