# Generated by Django 5.0 on 2024-01-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='kind',
            field=models.CharField(choices=[('1', 'customer'), ('2', 'consultant')], default='1', max_length=10),
        ),
    ]
